### ISSUE TITLE
include awesome-ts-loader

### ISSUE THREAD

**Issue by adrianabreu** [adrianabreu/chuck-norris-angular-client#18]
https://github.com/s-panferov/awesome-typescript-loader is faster than the ts-loader we're using currently.

**Comment by adrianabreu** [comment]
Due to incompatibilities with ui/router, this goes on standby until release of 8.2.0 https://github.com/developit/preact/issues/735

**Comment by adrianabreu** [comment]
in fact preact is used in ui/router VISUALIZER, which is just a tool for development. Shall we remove it? @vcollado

**Comment by vcollado** [comment]
it's ok
